server:
  port: ${PORT:8099}

# configure eureka client
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://user:password@localhost:8761/eureka/

# custom attribute for the actuator info endpoint
info:
  app:
    name: duff-service
    
# give the application a name
spring:
  application:
    name: duff-service
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  jpa:  
    hibernate:
      ddl-auto: update  
      
# disable actuagor security for endpoints 
management:
  security:
    enabled: false

# custom logging settings
logging:
  level:
      - ".=info"
      - "com.memorynotfound=debug"
      - "org.springframework=info"
      
spotify:
  clientId: 70bb62fd56414fd599d931a7c78ebd3b
  clientSecret: 7ca712d4c3844df1b5728b2e1d62fb63